<a href="https://colab.research.google.com/github/karanveer-sharma/pythontraining_with_ai/blob/main/assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Dataset 1: Employees Table
emp_data = {
    'Emp_ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Rajan', 'Anurag', 'Manya Gupta', 'Priya', 'Abhinav Garg', 'Frank'],
    'Dept_ID': ['D1', 'D1', 'D2', 'D3', 'D2', np.nan], # Frank has no Dept
    'Salary': [70000, 80000, 120000, 90000, 115000, 60000],
    'Join_Date': ['2023-01-15', '2023-02-10', '2022-05-20', '2021-08-15', '2024-01-01', '2023-06-30']
}
df_emp = pd.DataFrame(emp_data)

# Dataset 2: Departments Table
dept_data = {
    'Dept_ID': ['D1', 'D2', 'D3', 'D4'],
    'Dept_Name': ['HR', 'Engineering', 'Marketing', 'Sales'],
    'Location': ['Banglore', 'Hyderabad', 'Noida', 'Gurugram']
}
df_dept = pd.DataFrame(dept_data)

print("--- Employees ---")
display(df_emp)
print("\n--- Departments ---")
display(df_dept)

--- Employees ---

   Emp_ID          Name Dept_ID  Salary   Join_Date
0     101         Rajan      D1   70000  2023-01-15
1     102        Anurag      D1   80000  2023-02-10
2     103   Manya Gupta      D2  120000  2022-05-20
3     104         Priya      D3   90000  2021-08-15
4     105  Abhinav Garg      D2  115000  2024-01-01
5     106         Frank     NaN   60000  2023-06-30

--- Departments ---

  Dept_ID    Dept_Name   Location
0      D1           HR   Banglore
1      D2  Engineering  Hyderabad
2      D3    Marketing      Noida
3      D4        Sales   Gurugram

In [ ]:
new_hire_data = {
    'Emp_ID': [107],
    'Name': ['Harman'],
    'Dept_ID': ['D4'],
    'Salary': [90000],
    'Join_Date': ['2025-09-10']
}
new_hire = pd.DataFrame(new_hire_data)
df_emp = pd.concat([df_emp, new_hire], ignore_index=True)
display(df_emp)

   Emp_ID          Name Dept_ID  Salary   Join_Date
0     101         Rajan      D1   70000  2023-01-15
1     102        Anurag      D1   80000  2023-02-10
2     103   Manya Gupta      D2  120000  2022-05-20
3     104         Priya      D3   90000  2021-08-15
4     105  Abhinav Garg      D2  115000  2024-01-01
5     106         Frank     NaN   60000  2023-06-30
6     107        Harman      D4   90000  2025-09-10

In [ ]:
df_full = pd.merge(df_emp, df_dept, on='Dept_ID', how='left')
display(df_full)

   Emp_ID          Name Dept_ID  Salary   Join_Date    Dept_Name   Location
0     101         Rajan      D1   70000  2023-01-15           HR   Banglore
1     102        Anurag      D1   80000  2023-02-10           HR   Banglore
2     103   Manya Gupta      D2  120000  2022-05-20  Engineering  Hyderabad
3     104         Priya      D3   90000  2021-08-15    Marketing      Noida
4     105  Abhinav Garg      D2  115000  2024-01-01  Engineering  Hyderabad
5     106         Frank     NaN   60000  2023-06-30          NaN        NaN
6     107        Harman      D4   90000  2025-09-10        Sales   Gurugram

In [ ]:
mean_salary=df_full.groupby(df_full["Dept_ID"])["Salary"].mean()
display(mean_salary)

Dept_ID
D1     75000.0
D2    117500.0
D3     90000.0
D4     90000.0
Name: Salary, dtype: float64

In [ ]:
df_full["Avg_salary"]=df_full["Dept_ID"].map(mean_salary)
display(df_full)

,Emp_ID,Name,Dept_ID,Salary,Join_Date,Dept_Name,Location,Avg_salary
0,101,Rajan,D1,70000,2023-01-15,HR,Banglore,75000.0
1,102,Anurag,D1,80000,2023-02-10,HR,Banglore,75000.0
2,103,Manya Gupta,D2,120000,2022-05-20,Engineering,Hyderabad,117500.0
3,104,Priya,D3,90000,2021-08-15,Marketing,Noida,90000.0
4,105,Abhinav Garg,D2,115000,2024-01-01,Engineering,Hyderabad,117500.0
5,106,Frank,NaN,60000,2023-06-30,NaN,NaN,NaN
6,107,Harman,D4,90000,2025-09-10,Sales,Gurugram,90000.0

In [ ]:
higher_salary=df_full[df_full["Salary"]>df_full["Avg_salary"]]
print("Employees with higher salary than department average:")
display(higher_salary)

Employees with higher salary than department average:

,Emp_ID,Name,Dept_ID,Salary,Join_Date,Dept_Name,Location,Avg_salary
1,102,Anurag,D1,80000,2023-02-10,HR,Banglore,75000.0
2,103,Manya Gupta,D2,120000,2022-05-20,Engineering,Hyderabad,117500.0

In [ ]:
dp_loc=df_full.groupby(df_full["Dept_ID"])["Location"].first()
display(dp_loc)

Dept_ID
D1     Banglore
D2    Hyderabad
D3        Noida
D4     Gurugram
Name: Location, dtype: object

In [ ]:
bng=df_full.loc[df_full["Location"]=="Banglore"]
display(bng)

   Emp_ID    Name Dept_ID  Salary   Join_Date Dept_Name  Location  Avg_salary
0     101   Rajan      D1   70000  2023-01-15        HR  Banglore     75000.0
1     102  Anurag      D1   80000  2023-02-10        HR  Banglore     75000.0

In [ ]:
df_pivot=pd.pivot_table(df_full,values="Salary",index="Dept_ID",columns="Location",aggfunc="mean")
display(df_pivot)

Location  Banglore  Gurugram  Hyderabad    Noida
Dept_ID
D1         75000.0       NaN        NaN      NaN
D2             NaN       NaN   117500.0      NaN
D3             NaN       NaN        NaN  90000.0
D4             NaN   90000.0        NaN      NaN

In [ ]:
df_melt=pd.melt(df_pivot.reset_index(),id_vars="Dept_ID",var_name="Location",value_name="Avg_Salary")
display(df_melt)

   Dept_ID   Location  Avg_Salary
0       D1   Banglore     75000.0
1       D2   Banglore         NaN
2       D3   Banglore         NaN
3       D4   Banglore         NaN
4       D1   Gurugram         NaN
5       D2   Gurugram         NaN
6       D3   Gurugram         NaN
7       D4   Gurugram     90000.0
8       D1  Hyderabad         NaN
9       D2  Hyderabad    117500.0
10      D3  Hyderabad         NaN
11      D4  Hyderabad         NaN
12      D1      Noida         NaN
13      D2      Noida         NaN
14      D3      Noida     90000.0
15      D4      Noida         NaN

In [ ]:
print(df_full["Dept_Name"].memory_usage(deep=True),"bytes")

498 bytes

In [ ]:
df_full["Bonus_vec"]=df_full["Salary"]*0.10
df_full["Bonus_vec"].head(3)

0     7000.0
1     8000.0
2    12000.0
Name: Bonus_vec, dtype: float64

In [ ]:
def complex_bonus(x):
  if x>100000:
    return x*0.15
  else:
    return x*0.05
df_full["Bonus_Complex"]= df_full["Salary"].apply(complex_bonus)
df_full["Bonus_Complex"].head(3)

0     3500.0
1     4000.0
2    18000.0
Name: Bonus_Complex, dtype: float64

In [ ]:
df_full["First_name"]=df_full["Name"].str.split(' ').str[0]
hr_employes=df_full[df_full["Dept_Name"].str.contains("Eng", na = False)]
print("Engineering")
display(hr_employes)

Engineering

,Emp_ID,Name,Dept_ID,Salary,Join_Date,Dept_Name,Location,Avg_salary,Bonus_vec,Bonus_Complex,First_name
2,103,Manya Gupta,D2,120000,2022-05-20,Engineering,Hyderabad,117500.0,12000.0,18000.0,Manya
4,105,Abhinav Garg,D2,115000,2024-01-01,Engineering,Hyderabad,117500.0,11500.0,17250.0,Abhinav

In [ ]:
df_full["Join_date"]=pd.to_datetime(df_full["Join_Date"])
df_full["Join_year"]=df_full["Join_date"].dt.year
df_full["Join_month"]=df_full["Join_date"].dt.month
df_full["Join_day"]= df_full["Join_date"].dt.day
display(df_full[["Name", "Join_date","Join_year","Join_month","Join_day"]])

           Name  Join_date  Join_year  Join_month  Join_day
0         Rajan 2023-01-15       2023           1        15
1        Anurag 2023-02-10       2023           2        10
2   Manya Gupta 2022-05-20       2022           5        20
3         Priya 2021-08-15       2021           8        15
4  Abhinav Garg 2024-01-01       2024           1         1
5         Frank 2023-06-30       2023           6        30
6        Harman 2025-09-10       2025           9        10

In [ ]:
df_sorted =df_full.sort_values("Join_date")
df_sorted[["Emp_ID","Salary","Join_date"]]

   Emp_ID  Salary  Join_date
3     104   90000 2021-08-15
2     103  120000 2022-05-20
0     101   70000 2023-01-15
1     102   80000 2023-02-10
5     106   60000 2023-06-30
4     105  115000 2024-01-01
6     107   90000 2025-09-10

In [ ]:
df_sorted["Rolling_Avg_salary"]=df_sorted["Salary"].rolling(window=2).mean()
print("Rolling Average Salary:")
display(df_sorted[["Join_date","Salary","Rolling_Avg_salary"]])

Rolling Average Salary:

   Join_date  Salary  Rolling_Avg_salary
3 2021-08-15   90000                 NaN
2 2022-05-20  120000            105000.0
0 2023-01-15   70000             95000.0
1 2023-02-10   80000             75000.0
5 2023-06-30   60000             70000.0
4 2024-01-01  115000             87500.0
6 2025-09-10   90000            102500.0

In [ ]:
high_earners_nd = df_full.query("Salary>80000 and Location =='Noida'")
print("High earners in Noida :")
display(high_earners_nd[["Name","Salary","Location"]])

High earners in Noida :

    Name  Salary Location
3  Priya   90000    Noida