<a href="https://colab.research.google.com/github/karanveer-sharma/pythontraining_with_ai/blob/main/socialanalytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
social = {
    "Handle": ["@techguru", "Gamer_123", "@Beauty_lush","Travel_Boy"],
    "Followers": ["1.2M","500k","2.5M","900"],
    "Avg_likes":["50k","12000", "150k","45" ],
    "Category":["Tech","gaming","Beauty","travel"],
    "Verified":["Yes","No","Yes","No"]
    }

In [ ]:
df_social=pd.DataFrame(social)
print("social Media data")
display(df_social)

social Media data

         Handle Followers Avg_likes Category Verified
0     @techguru      1.2M       50k     Tech      Yes
1     Gamer_123      500k     12000   gaming       No
2  @Beauty_lush      2.5M      150k   Beauty      Yes
3    Travel_Boy       900        45   travel       No

In [ ]:
df_social["Handle"]=df_social["Handle"].str.replace("@","", regex=False)

In [ ]:
df_social["Handle"].head()

0       techguru
1      Gamer_123
2    Beauty_lush
3     Travel_Boy
Name: Handle, dtype: object

In [ ]:
def convert_to_no(value_str):
  value_str = str(value_str).lower()
  if "m"in value_str:
    return float(value_str.replace("m",""))*1000000
  elif"k" in value_str:
    return float(value_str.replace("k",""))*1000
  else:
    return float(value_str)

In [ ]:
df_social["Followers_num"]=df_social["Followers"].apply(convert_to_no)
df_social["Avg_likes_num"]=df_social["Avg_likes"].apply(convert_to_no)
df_social.head()

,Handle,Followers,Avg_likes,Category,Verified,Followers_num,Avg_likes_num
0,techguru,1.2M,50k,Tech,Yes,1200000.0,50000.0
1,Gamer_123,500k,12000,gaming,No,500000.0,12000.0
2,Beauty_lush,2.5M,150k,Beauty,Yes,2500000.0,150000.0
3,Travel_Boy,900,45,travel,No,900.0,45.0

In [ ]:
df_social["Category"]=df_social["Category"].str.capitalize()
df_social["Category"].head()

0      Tech
1    Gaming
2    Beauty
3    Travel
Name: Category, dtype: object

In [ ]:
df_social["Followers_num"].head()

0    1200000.0
1     500000.0
2    2500000.0
3        900.0
Name: Followers_num, dtype: float64

In [ ]:
df_social["Engagement_rate"]= (df_social["Avg_likes_num"]/df_social["Followers_num"])*100
top_creators= df_social[df_social["Engagement_rate"]>3.0]
print("\ntop creators")
display(top_creators)

top creators

,Handle,Followers,Avg_likes,Category,Verified,Followers_num,Avg_likes_num,Engagement_rate
0,techguru,1.2M,50k,Tech,Yes,1200000.0,50000.0,4.166667
2,Beauty_lush,2.5M,150k,Beauty,Yes,2500000.0,150000.0,6.000000
3,Travel_Boy,900,45,Travel,No,900.0,45.0,5.000000

In [ ]:
Log_data={
    "Log_entry": [
        "192.168.1.1 - GET /login - 200 OK - 15ms",
        "192.168.1.5 - POST /upload - 500 Error - 2000ms",
        "10.0.0.4 - GET /home - 200 OK - 12ms",
        "192.168.1.15 - GET/admin - 403 Forbidden - 5ms",
        "10.0.0.8 -GET/dashboard - 200 OK - 1100ms"    ]
}

In [ ]:
df_log=pd.DataFrame(Log_data)
print("log data")
display(df_log)

log data

                                         Log_entry
0         192.168.1.1 - GET /login - 200 OK - 15ms
1  192.168.1.5 - POST /upload - 500 Error - 2000ms
2             10.0.0.4 - GET /home - 200 OK - 12ms
3   192.168.1.15 - GET/admin - 403 Forbidden - 5ms
4        10.0.0.8 -GET/dashboard - 200 OK - 1100ms

In [ ]:
parsed_logs=df_log["Log_entry"].str.split(" - ", expand=True)
parsed_logs.columns =["Ip_address","Request","Status","Latency"]
print("\nParsed logs")
display(parsed_logs)

Parsed logs

                Ip_address       Request         Status Latency
0              192.168.1.1    GET /login         200 OK    15ms
1              192.168.1.5  POST /upload      500 Error  2000ms
2                 10.0.0.4     GET /home         200 OK    12ms
3             192.168.1.15     GET/admin  403 Forbidden     5ms
4  10.0.0.8 -GET/dashboard        200 OK         1100ms    None

In [ ]:
parsed_logs["Latency_value"] = parsed_logs["Latency"].astype(str).str.replace("ms", "").astype(float)
parsed_logs["Latency_value"].head()

0      15.0
1    2000.0
2      12.0
3       5.0
4       NaN
Name: Latency_value, dtype: float64

In [ ]:
suspicious= parsed_logs[parsed_logs["Status"].str.contains("403")]
print("\n security alert (admin access ) :")
display(suspicious[["Ip_address", "Request"]])

 security alert (admin access ) :

     Ip_address    Request
3  192.168.1.15  GET/admin

In [ ]:
slow_query =parsed_logs[parsed_logs["Latency_value"]>1000]
print("\n slow response")
display(slow_query[["Request","Latency_value"]])

 slow response

        Request  Latency_value
1  POST /upload         2000.0

In [ ]:

import numpy as np
import math

PI = 3.14

In [ ]:

def calculate_area(num):

  return PI * num**2
print(calculate_area(2))

12.56

In [ ]:
def divide(a, b):
    return a / b
print(divide(10, 2))

5.0

In [ ]:
def append_item(item, my_list=[]):
    my_list.append(item)
    return my_list
print(append_item(1,[1,2,3,4]))
print(append_item(2,[1,2,3,4]))

[1, 2, 3, 4, 1]
[1, 2, 3, 4, 2]

In [ ]:
def recursive_function(n):
    return n + 1
print(recursive_function(4))

5

In [ ]:
def string_indexing():
    text = "Hello"
    return text[0:5]
print(string_indexing())

Hello

In [ ]:
def dictionary_access():
    data = {"name": "Alice","age":19}
    return data["age"]
print(dictionary_access())

19

In [ ]:
def type_mismatch():
    number = 10
    text = 5
    return number + text
print(type_mismatch())

15

In [ ]:
def variable_scope(x):
    print(x)
variable_scope()